version: 0.1
phases:
  install:
    commands:
      - npm install
      - aws cloudformation package --template-file appspec.yaml --s3-bucket ivan-code-deploy
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - appspec.yaml
    - outputSamTemplate.yaml