AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ivan-line-bot
Resources:
  LineBot:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        LineBotAPI:
          Type: Api
          Properties:
            Path: /
            Method: POST